#!/bin/bash

mkdir /bin/monitoringProcces
touch /bin/monitoringProcces/start_monitoring.sh

cp DetectionAnomaliesTraffic.py /bin/monitoringProcces
cp ManagerForDetectionScrypt.py /bin/monitoringProcces


echo "#!/bin/bash" >> /bin/monitoringProcces/start_monitoring.sh
echo "python3 ManagerForDetectionScrypt.py &" >> /bin/monitoringProcces/start_monitoring.sh

chmod +x /bin/monitoringProcces/start_monitoring.sh

echo "/bin/monitoringProcces/start_monitoring.sh" >> /etc/rc.local

/bin/monitoringProcces/start_monitoring.sh
