#!/bin/bash

mkdir /bin/monitoringProcсes
touch /bin/monitoringProcсes/start_monitoring.sh

cp DetectionAnomaliesTraffic.py /bin/monitoringProcсes
cp ManagerForDosDetectionScrypt.py /bin/monitoringProcсes


echo "#!/bin/bash" >> /bin/monitoringProcсes/start_monitoring.sh
echo "python3 ManagerForDosDetectionScrypt.py &" >> /bin/monitoringProcсes/start_monitoring.sh

chmod +x /bin/monitoringProcсes/start_monitoring.sh

echo "/bin/monitoringProcсes/start_monitoring.sh" >> /etc/rc.local

/bin/monitoringProcсes/start_monitoring.sh
