#!/bin/bash


cp DetectionAnomaliesTraffic.py /bin/monitoringProcess
cp ManagerForDosDetectionScrypt.py /bin/monitoringProcess

# Создание скрипта на Bash для запуска file1 и file2
touch /bin/monitoringProcess/start_monitoring.sh

echo "#!/bin/bash" >> /bin/monitoringProcess/start_monitoring.sh
echo "python3 ManagerForDosDetectionScrypt.py END" >> /bin/monitoringProcess/start_monitoring.sh

chmod +x /bin/monitoringProcess/start_monitoring.sh

echo "/bin/monitoringProcess/start_monitoring.sh" >> /etc/rc.local

/bin/monitoringProcess/start_monitoring.sh
